- name: Installing the Prerequisite packages for Master Node
  yum:  name={{ item }} state=installed
  with_items:
      - docker
      - docker-logrotate
      - kubernetes
      - flanneld

- name: Configuring the Kublet minion node
  template: src={{ item.src }} dest={{ item.dest }}
  with_items:
      - { src: "kubelet", dest: "/etc/kubernetes/kubelet" }
      - { src: "config", dest: "/etc/kubernetes/config" }
      - { src: "flanneld", dest: "/etc/sysconfig/flanneld" }


- name: Starting all the related services for the Minions
  service: name={{ item }} state=started enabled=true
  with_items:
      - kube-proxy 
      - kubelet 
      - docker 
      - flanneld
